apiVersion: v1
entries:
  helm-test:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2024-11-21T17:02:46.398367283-06:00"
    description: Helm chart para un despliegue de backend y frontend con configuración
      dinámica.
    digest: a2321c60152db8d6a1ba879690776283390b144f4519149ffd706dbe8d9844f2
    keywords:
    - frontend
    - backend
    - helm
    maintainers:
    - email: carlosmartz1995@gmail.com
      name: Carlos M.
      url: https://github.com/2730538920101
    name: helm-test
    sources:
    - https://github.com/2730538920101/TestHelmAPI
    type: application
    urls:
    - https://2730538920101.github.io/TestHelmAPI/chart/helm-test-1.0.0.tgz
    version: 1.0.0
    readme: https://github.com/2730538920101/TestHelmAPI/blob/main/chart/README.md
generated: "2024-11-21T17:02:46.397435283-06:00"
