services:
  backend:
    build:
      context: ./backend
    image: carlosmz87/test_helm_backend:latest
    container_name: test_helm_backend_container
    ports:
      - "5000:5000"
    networks:
      - test_helm_network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        - API_SERVER=${API_SERVER}
    image: carlosmz87/test_helm_frontend:latest
    container_name: test_helm_frontend_container
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - test_helm_network
    environment:
      - API_SERVER=${API_SERVER}
      - NODE_ENV=production

networks:
  test_helm_network:
    driver: bridge
