apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helm-test.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "helm-test.labels" . | nindent 4 }}
    component: backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
  type: ClusterIP