apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helm-test.labels" . | nindent 4 }}
data:
  NODE_ENV: "{{ .Values.configMap.nodeEnv }}"
