apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helm-test.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "helm-test.labels" . | nindent 4 }}
    component: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
  type: LoadBalancer