apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helm-test.labels" . | nindent 4 }}
    component: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      {{- include "helm-test.labels" . | nindent 6 }}
      component: frontend
  template:
    metadata:
      labels:
        {{- include "helm-test.labels" . | nindent 8 }}
        component: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image }}"
        ports:
        - containerPort: {{ .Values.frontend.port }}
        envFrom:
        - configMapRef:
            name: env-config
        - secretRef:
            name: frontend-secrets
        {{- include "helm-test.resources" . | nindent 8 }}