apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helm-test.labels" . | nindent 4 }}
type: Opaque
data:
  API_SERVER: "{{ .Values.secrets.apiServer | b64enc }}"
