apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: helm-test
  labels:
    app: helm-test
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm-test
      component: backend
  template:
    metadata:
      labels:
        app: helm-test
        component: backend
    spec:
      containers:
      - name: backend
        image: carlosmz87/test_helm_backend:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: helm-test
  labels:
    app: helm-test
spec:
  selector:
    app: helm-test
    component: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
