apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: helm-test
  labels:
    app: helm-test
spec:
  selector:
    app: helm-test
    component: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
