apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: helm-test
  labels:
    app: helm-test
spec:
  selector:
    app: helm-test
    component: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
