apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
  namespace: helm-test
  labels:
    app: helm-test
type: Opaque
data:
  API_SERVER: aHR0cDovL2JhY2tlbmQtc2VydmljZS5oZWxtLXRlc3Quc3ZjLmNsdXN0ZXIubG9jYWw6NTAwMC9hcGk=
  ## echo -n "http://backend-service.helm-test.svc.cluster.local:5000/api" | base64 para obtener el secret en base 64
